#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPRO_SCRIPT="$SCRIPT_DIR/reproduce_wersja_aj.sh"

: "${TRAIN_SCRIPT:=scripts/train/math/math_decomposer_selector_hybrid_shared.sh}"
: "${ORCHESTRATOR_MODEL:=Qwen/Qwen3-8B}"
: "${WORKER_MODEL:=${ORCHESTRATOR_MODEL}}"
: "${ORCHESTRATOR_TRAINABLE:=true}"
: "${ORCHESTRATOR_OPTIMIZATION_MODE:=prompt}"
: "${WORKER_TRAINABLE:=false}"
: "${WORKER_OPTIMIZATION_MODE:=prompt}"
: "${WANDB_NAME:=math_decomposer_selector_hybrid_shared}"

sbatch \
  --export="ALL,HOST_REPO_DIR=$SCRIPT_DIR,TRAIN_SCRIPT=$TRAIN_SCRIPT,ORCHESTRATOR_MODEL=$ORCHESTRATOR_MODEL,WORKER_MODEL=$WORKER_MODEL,ORCHESTRATOR_TRAINABLE=$ORCHESTRATOR_TRAINABLE,ORCHESTRATOR_OPTIMIZATION_MODE=$ORCHESTRATOR_OPTIMIZATION_MODE,WORKER_TRAINABLE=$WORKER_TRAINABLE,WORKER_OPTIMIZATION_MODE=$WORKER_OPTIMIZATION_MODE,WANDB_NAME=$WANDB_NAME" \
  "$@" \
  "$REPRO_SCRIPT"
