#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPRO_SCRIPT="$SCRIPT_DIR/reproduce_wersja_aj.sh"

: "${TRAIN_SCRIPT:=scripts/train/math/math_decomposer_selector_hybrid_separate.sh}"
: "${DECOMPOSER_MODEL:=Qwen/Qwen3-8B}"
: "${SELECTOR_MODEL:=Qwen/Qwen3-8B}"
: "${WORKER_MODEL:=Qwen/Qwen3-8B}"
: "${DECOMPOSER_TRAINABLE:=true}"
: "${DECOMPOSER_OPTIMIZATION_MODE:=prompt}"
: "${SELECTOR_TRAINABLE:=true}"
: "${SELECTOR_OPTIMIZATION_MODE:=prompt}"
: "${WORKER_TRAINABLE:=false}"
: "${WORKER_OPTIMIZATION_MODE:=prompt}"
: "${WANDB_NAME:=math_decomposer_selector_hybrid_separate}"

sbatch \
  --export="ALL,HOST_REPO_DIR=$SCRIPT_DIR,TRAIN_SCRIPT=$TRAIN_SCRIPT,DECOMPOSER_MODEL=$DECOMPOSER_MODEL,SELECTOR_MODEL=$SELECTOR_MODEL,WORKER_MODEL=$WORKER_MODEL,DECOMPOSER_TRAINABLE=$DECOMPOSER_TRAINABLE,DECOMPOSER_OPTIMIZATION_MODE=$DECOMPOSER_OPTIMIZATION_MODE,SELECTOR_TRAINABLE=$SELECTOR_TRAINABLE,SELECTOR_OPTIMIZATION_MODE=$SELECTOR_OPTIMIZATION_MODE,WORKER_TRAINABLE=$WORKER_TRAINABLE,WORKER_OPTIMIZATION_MODE=$WORKER_OPTIMIZATION_MODE,WANDB_NAME=$WANDB_NAME" \
  "$@" \
  "$REPRO_SCRIPT"
